### PR TITLE
Update regex for Swiss VAT numbers to match new format based on Swiss BID number

### PR DESCRIPTION
**Pull request by danielterhorst**
Based on:
- https://www.ch.ch/en/value-added-tax-number-und-business-identification-number/
- https://en.wikipedia.org/wiki/VAT_identification_number

### CODE REVIEW

**Comment by ralphje** [comment]
I don't think the MWST/TVA/IVA is actually part of the CH VAT number. I believe it is actually part of the formatting of the number. We should remove that part in cleanup from the data, and format it accordingly for display. I think this is the best approach, as the choice for MWST, TVA or IVA actually seems te depend on the language context when it is displayed, not when it is entered. 

See for instance the tables on http://www.bfs.admin.ch/bfs/portal/de/index/themen/00/05/blank/03/02.html (e.g. section Mehrwertsteuergruppe), the MWST-part is not shown in these tables. It would have it was actually part of the number itself.

On the other hand, I am still doubting whether the E-part of CHE should be part of the VAT number. It's there because Switzerland uses an alpha-3 code instead of an alpha-2.

**Comment by eriktelepovsky** [comment]
Hello. Please add "E" as a part of Swiss VAT number. Check this out: "CHE112355309"

https://vatapp.net/vat-number-check

**Comment by eriktelepovsky** [comment]
**How to check Swiss VAT number?**

Enter Swiss VAT number in the following format: CHE and number that can have 9 digits MWST/TVA/IVA. MWST/TVA/IVA part is optional. Swiss VAT number validation results are obtained in real time from UID register, The Swiss Federal Statistical Office (FSO) , Switzerland.

**Comment by ralphje** [comment]
I do agree that I was a bit too stringent five years ago. The intermediate solution would be to use the display class to fix this, though I agree it is probably best to store the E in the database at some point.

**Comment by eriktelepovsky** [comment]
Perfect :-) I am looking forward to accept pull request.

**Comment by eriktelepovsky** [comment]
Hello. Can you merge this PR, please?

**Comment by ralphje** [comment]
Not directly, I still do not agree that the ``TVA|MWST|IVA`` is part of the Swiss number. Furthermore, I do not think we should accept the E and keep it optional. It is either the E in there, or not. We should also adjust https://github.com/ralphje/django-internationalflavor/blob/master/internationalflavor/vat_number/validators.py#L22 to make sure that it inserts it when needed, so that this change is as transparent as possible.

**Pull request closed without merging**
